version: '2.1'

services:

  # polydiploma su=ystem
  polydiploma:
    image: rockduatra/polydiploma
    container_name: polydiploma

    environment: 
      - hyperplanning_host=hyperplanning
      - hyperplanning_port=9090
    expose: 
      - "8080"
    ports: 
      - "8080:8080"
    depends_on:
      - hyperplanning
  
  # hyperplanning
  hyperplanning:
    image: rockduatra/hyperplanning
    container_name: hyperplanning
    expose:
      - "9090"
    ports:
      - "9090:9090"